# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

class Class(object):
    PrivateCars = 0
    DoubleDeckerBus = 1
    SingleDeckerBus = 2
    Taxi = 3
    MiniBus = 4
    Vans = 5
    LightTrucks = 6
    Motorbikes = 7
    CraneTruck = 8
    CylindricalTruck = 9

